---

- name: "Configure {{ hadoop_core_site_file }}"
  template:
    src: core-site.xml.j2
    dest: "{{ hadoop_core_site_file }}"
    validate: "xmllint %s"
  when: hadoop_core_site_file
  notify:
    - Restart namenode

- name: "Configure {{ hadoop_hdfs_site_file }}"
  template:
    src: hdfs-site.xml.j2
    dest: "{{ hadoop_hdfs_site_file }}"
    validate: "xmllint %s"
  when: hadoop_hdfs_site_file
  notify:
    - Restart namenode

- name: "Configure {{ hadoop_mapred_site_file }}"
  template:
    src: mapred-site.xml.j2
    dest: "{{ hadoop_mapred_site_file }}"
    validate: "xmllint %s"
  when: hadoop_mapred_site_file
  notify:
    - Restart namenode

- name: "Configure {{ hadoop_yarn_site_file }}"
  template:
    src: yarn-site.xml.j2
    dest: "{{ hadoop_yarn_site_file }}"
    validate: "xmllint %s"
  when: hadoop_yarn_site_file
  notify:
    - Restart namenode
