---

- name: "Configure {{ hadoop_core_site_file }}"
  template:
    src: core-site.xml.j2
    dest: "{{ hadoop_core_site_file }}"
    validate: "xmllint %s"
  when: hadoop_core_site_file
  register: core_site
  notify:
    - Restart namenode

- name: "Configure {{ hadoop_hdfs_site_file }}"
  template:
    src: hdfs-site.xml.j2
    dest: "{{ hadoop_hdfs_site_file }}"
    validate: "xmllint %s"
  when: hadoop_hdfs_site_file
  register: hdfs_site
  notify:
    - Restart namenode

- name: "Configure {{ hadoop_mapred_site_file }}"
  template:
    src: mapred-site.xml.j2
    dest: "{{ hadoop_mapred_site_file }}"
    validate: "xmllint %s"
  when: hadoop_mapred_site_file
  register: mapred_site
  notify:
    - Restart namenode

- name: "Configure {{ hadoop_yarn_site_file }}"
  template:
    src: yarn-site.xml.j2
    dest: "{{ hadoop_yarn_site_file }}"
    validate: "xmllint %s"
  when: hadoop_yarn_site_file
  register: yarn_site
  notify:
    - Restart namenode

# XXX restart hadoop services when hadoop_config_changed is true
# you cannot "notify" here because zkfc is not enabled when standalone
- set_fact:
    hadoop_config_changed: true
  when: "{{ core_site.changed or hdfs_site.changed or mapred_site.changed or yarn_site.changed or (hadoop_config_changed is defined and hadoop_config_changed) }}"
