---

- command: "zkCli.sh -server {{ hadoop_namenode_zookeeper_nodes | random }} -cmd 'ls /hadoop-ha'"
  register: zkcli_result
  changed_when: false

- command: hdfs zkfc -formatZK -nonInteractive
  become: yes
  become_user: "{{ hadoop_namenode_user }}"
  become_method: sudo
  when: "{{ not '[' ~ hadoop_namenode_dfs_nameservices ~ ']' in zkcli_result.stdout_lines }}"

- name: Start zkfc
  service:
    name: zkfc
    enabled: true
    state: started
