---

- name: Install hadoop
  pkgng:
    name: hadoop2
    state: present

- name: install py27-lxml
  pkgng:
    name: py27-lxml
    state: present

- name: fix status command in namenode
  patch:
    src: patch-namenode
    dest: /usr/local/etc/rc.d/namenode

- name: fix status command in resourcemanager
  patch:
    src: patch-resourcemanager
    dest: /usr/local/etc/rc.d/resourcemanager
