---
# tasks file for ansible-role-hadoop

- include_vars: "{{ ansible_os_family }}.yml"

- include: install-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- name: Create slaves file
  template:
    src: slaves.j2
    dest: "{{ hadoop_conf_dir }}/slaves"
  notify:
    - Restart namenode

- name: Create log directory
  file:
    path: "{{ hadoop_namenode_log_dir }}"
    mode: 0775
    owner: "{{ hadoop_namenode_user }}"
    group: "{{ hadoop_namenode_group }}"
    state: directory
  notify:
    - Restart namenode

- name: Create db directory
  file:
    path: "{{ hadoop_namenode_db_dir }}"
    mode: 0755
    owner: "{{ hadoop_namenode_user }}"
    group: "{{ hadoop_namenode_group }}"
    state: directory
  notify:
    - Restart namenode

- name: Create dfs_hosts
  template:
    dest: "{{ hadoop_namenode_dfs_hosts_file }}"
    src: dfs_hosts.j2
    owner: "{{ hadoop_namenode_user }}"
    group: "{{ hadoop_namenode_group }}"
    mode: 0644

- name: Create dfs.namenode.name.dir
  file:
    path: "{{ hadoop_namenode_dfs_namenode_name_dir }}"
    mode: 0755
    owner: "{{ hadoop_namenode_user }}"
    group: "{{ hadoop_namenode_group }}"
    state: directory
  notify:
    - Restart namenode

- include: configure-xml.yml

- include: ha-namenode.yml
  when:
    - hadoop_namenode_enable_ha

- include: standalone-namenode.yml
  when:
    - not hadoop_namenode_enable_ha

- name: Start hadoop namenode
  service:
    name: "{{ hadoop_namenode_service }}"
    state: started

- name: Wait for namenode to listen on IP address hadoop_namenode_host and port hadoop_namenode_port (tasks/main.yml)
  # XXX in case of Java application, you cannot be sure if it has started
  # successfully
  wait_for:
    host: "{{ hadoop_namenode_host }}"
    port: "{{ hadoop_namenode_port }}"

- include: ha-zkfc.yml
  when:
    - hadoop_namenode_enable_ha
